import type { AgentConfig } from '../../src/config/env.js';

export function testConfig(overrides: Partial<AgentConfig> = {}): AgentConfig {
  return {
    port: 0,
    publicBaseUrl: 'https://agent.example.test',
    chatEndpointUrl: 'https://chat.example.test/chat',
    sendblueApiBaseUrl: 'https://api.sendblue.example.test',
    sendblueApiV2BaseUrl: 'https://api-v2.sendblue.example.test',
    sendblueApiKeyId: 'test-key-id',
    sendblueApiSecretKey: 'test-secret-key',
    sendblueFromNumber: '+15552220000',
    sendblueWebhookSecret: 'test-webhook-secret',
    sendblueWebhookSecretHeader: 'x-sendblue-test-secret',
    chatEndpointTimeoutMs: 1000,
    redisUrl: undefined,
    conversationTtlSeconds: 86400,
    dedupeTtlSeconds: 86400,
    bufferBaseTimeoutMs: 0,
    bufferGrowthFactor: 1.25,
    bufferMaxTimeoutMs: 0,
    bufferNoiseMaxDeviation: 0,
    maxReprocessAttempts: 2,
    cancelledMessageMaxLength: 150,
    bufferQueueName: 'test-buffer-timers',
    outboundDeliveryTimeoutMs: 30000,
    userLookupUrl: undefined,
    identityResolverTimeoutMs: 0,
    outboundTypingIndicatorsEnabled: true,
    inboundTypingStateEnabled: true,
    readReceiptsEnabled: false,
    readReceiptDebounceMs: 0,
    typingStartDelayMs: 0,
    typingRefreshIntervalMs: 0,
    typingRefreshMaxMs: 0,
    agentDisplayName: 'sb-agent',
    validUserRequired: false,
    groupInvocationContentFallback: true,
    chatResponseParseTags: true,
    chatResponseTags: {
      message: 'message',
      noResponse: 'no_response',
      reaction: 'reaction',
      reply: 'reply'
    },
    sendblueContactsEnabled: false,
    sendblueContactsDefaultTags: [],
    sendblueContactsDedupeTtlSeconds: 86400,
    // Disable pre-emptive pacing in unit/integration tests by default —
    // the 1/s gate uses real setTimeout, which deadlocks tests that drive
    // multiple back-to-back outbound sends under vi.useFakeTimers. Tests
    // that need to verify pacing must override this.
    outboundRateLimitPerSecond: 0,
    outboundRateLimitPerHour: 2000,
    outboundRateLimitPerDay: 4000,
    inboundContactsPerDayWarnThreshold: 800,
    inboundContactsPerDayLimit: 1000,
    followUpDailyWarnThreshold: 160,
    followUpDailyLimit: 200,
    replyWindowHours: 24,
    transientRetryMaxAttempts: 3,
    transientRetryBaseMs: 1000,
    transientRetryMaxMs: 60000,
    smsLimitRetryIntervalMs: 3600000,
    smsLimitMaxAttempts: 24,
    adminApiToken: undefined,
    metricsLabelCardinalityLimit: 1000,
    readyRedisTimeoutMs: 500,
    ...overrides
  };
}
